addons:
  sonarcloud:
    organization: "zhengguorong-github" # the key of the org you chose at step #3
    token:
      secure: 9785888673923c2fa351fb7e92da6d406ed2c962 # encrypted value of your token
language: node_js
node_js:
  - '10'
install:
  - npm i
script:
  # - npm run test
  - sonar-scanner